name: "Terraform"

on: [push]

jobs:
  terraform:
  runs-on: ubuntu-latest
  steps:
    - name: checkoutheckout
      uses: actions/checkout@v3
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with 



